Support sparc-unknown-linux-gnu again
Currently, a patch is needed due to "undefined reference to `__sync_val_compare_and_swap_8'" error
(due to max_atomic_width is wrongly set to 64:
https://github.com/rust-lang/rust/blob/1.70.0/compiler/rustc_target/src/spec/sparc_unknown_linux_gnu.rs#L8)