Temporary disable static linking test for tier3 linux-musl
There is libunwind build issue since around 2022-12-16.

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `3`,
 right: `0`: Can't get object files from "/tmp/libunwind"', src/main.rs:181:5
```